"""
Extension service for CopySpell AI that runs on port 5001
This service allows expanding on initial content generated by the main application
"""
import os
import sys
import json
import asyncio
from typing import Dict, Any, Optional
from flask import Flask, request, jsonify, render_template_string
from flask_cors import CORS
import logging

# Add the project root to the Python path to import core modules
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from core.content_generator import ContentGenerator, RouterResult
from config.extension_prompts import build_extension_prompt, build_detailed_expansion_prompt
from config.settings import Settings

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

app = Flask(__name__)
CORS(app)  # Enable CORS for cross-origin requests

# Initialize the content generator
generator = ContentGenerator()

HTML_TEMPLATE = '''
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CopySpell AI Extension Service</title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            margin: 0;
            padding: 20px;
            min-height: 100vh;
            color: #333;
        }
        .container {
            max-width: 800px;
            margin: 0 auto;
            background: rgba(255, 255, 255, 0.95);
            border-radius: 15px;
            padding: 30px;
            box-shadow: 0 10px 30px rgba(0, 0, 0, 0.2);
            backdrop-filter: blur(10px);
        }
        h1 {
            color: #4a5568;
            text-align: center;
            margin-bottom: 30px;
            font-size: 2.2em;
        }
        .form-group {
            margin-bottom: 20px;
        }
        label {
            display: block;
            margin-bottom: 8px;
            font-weight: 600;
            color: #4a5568;
        }
        textarea, select {
            width: 100%;
            padding: 12px;
            border: 2px solid #e2e8f0;
            border-radius: 8px;
            font-size: 14px;
            transition: border-color 0.3s ease;
            resize: vertical;
        }
        textarea:focus, select:focus {
            outline: none;
            border-color: #667eea;
        }
        textarea {
            min-height: 150px;
        }
        button {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 12px 30px;
            border: none;
            border-radius: 8px;
            cursor: pointer;
            font-size: 16px;
            font-weight: 600;
            transition: transform 0.2s ease, box-shadow 0.2s ease;
        }
        button:hover {
            transform: translateY(-2px);
            box-shadow: 0 5px 15px rgba(102, 126, 234, 0.4);
        }
        button:disabled {
            opacity: 0.6;
            cursor: not-allowed;
            transform: none;
        }
        .result {
            margin-top: 30px;
            padding: 20px;
            background: #f7fafc;
            border-radius: 8px;
            border-left: 4px solid #667eea;
            display: none;
        }
        .result.show {
            display: block;
            animation: fadeIn 0.5s ease-in;
        }
        @keyframes fadeIn {
            from { opacity: 0; transform: translateY(10px); }
            to { opacity: 1; transform: translateY(0); }
        }
        .loading {
            display: none;
            text-align: center;
            margin: 20px 0;
        }
        .loading.show {
            display: block;
        }
        .spinner {
            border: 4px solid #f3f3f3;
            border-top: 4px solid #667eea;
            border-radius: 50%;
            width: 40px;
            height: 40px;
            animation: spin 1s linear infinite;
            margin: 0 auto;
        }
        @keyframes spin {
            0% { transform: rotate(0deg); }
            100% { transform: rotate(360deg); }
        }
        .info-box {
            background: #ebf8ff;
            border-left: 4px solid #4299e1;
            padding: 15px;
            margin-bottom: 20px;
            border-radius: 0 8px 8px 0;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>📝 CopySpell AI Extension Service</h1>
        
        <div class="info-box">
            <strong>How to use:</strong> Paste content generated by CopySpell AI and select how you'd like to expand it. 
            This service runs on port 5001 and uses the same AI providers as the main application.
        </div>
        
        <form id="extensionForm">
            <div class="form-group">
                <label for="initialContent">Initial Content to Extend:</label>
                <textarea id="initialContent" placeholder="Paste your initial content here..."></textarea>
            </div>
            
            <div class="form-group">
                <label for="expansionType">Expansion Type:</label>
                <select id="expansionType">
                    <option value="general">General Expansion</option>
                    <option value="details">Add More Details</option>
                    <option value="examples">Include Examples</option>
                    <option value="benefits">Highlight Benefits</option>
                    <option value="features">Elaborate Features</option>
                    <option value="applications">Explore Applications</option>
                    <option value="technical">Technical Depth</option>
                    <option value="creative">Creative Expansion</option>
                </select>
            </div>
            
            <div class="form-group">
                <label for="expansionFocus">Expansion Focus:</label>
                <select id="expansionFocus">
                    <option value="comprehensive">Comprehensive</option>
                    <option value="analytical">Analytical</option>
                    <option value="narrative">Narrative</option>
                    <option value="practical">Practical</option>
                    <option value="strategic">Strategic</option>
                    <option value="educational">Educational</option>
                    <option value="persuasive">Persuasive</option>
                    <option value="creative">Creative</option>
                </select>
            </div>
            
            <button type="submit">Extend Content</button>
        </form>
        
        <div class="loading" id="loadingIndicator">
            <div class="spinner"></div>
            <p>Extending your content...</p>
        </div>
        
        <div class="result" id="resultContainer">
            <h3>Extended Content:</h3>
            <div id="resultContent"></div>
        </div>
    </div>

    <script>
        document.getElementById('extensionForm').addEventListener('submit', async function(e) {
            e.preventDefault();
            
            const initialContent = document.getElementById('initialContent').value.trim();
            const expansionType = document.getElementById('expansionType').value;
            const expansionFocus = document.getElementById('expansionFocus').value;
            
            if (!initialContent) {
                alert('Please enter some content to extend.');
                return;
            }
            
            // Show loading indicator
            document.getElementById('loadingIndicator').classList.add('show');
            document.getElementById('resultContainer').classList.remove('show');
            document.querySelector('button[type="submit"]').disabled = true;
            
            try {
                const response = await fetch('/api/extend', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                    },
                    body: JSON.stringify({
                        initial_content: initialContent,
                        expansion_type: expansionType,
                        expansion_focus: expansionFocus
                    })
                });
                
                const data = await response.json();
                
                if (response.ok) {
                    document.getElementById('resultContent').textContent = data.result;
                    document.getElementById('resultContainer').classList.add('show');
                } else {
                    alert('Error: ' + data.error || 'Failed to extend content');
                }
            } catch (error) {
                console.error('Error:', error);
                alert('An error occurred while extending content.');
            } finally {
                // Hide loading indicator
                document.getElementById('loadingIndicator').classList.remove('show');
                document.querySelector('button[type="submit"]').disabled = false;
            }
        });
    </script>
</body>
</html>
'''

@app.route('/')
def home():
    """Serve the extension service homepage"""
    return render_template_string(HTML_TEMPLATE)

@app.route('/api/extend', methods=['POST'])
def extend_content():
    """API endpoint to extend initial content"""
    try:
        data = request.get_json()
        
        initial_content = data.get('initial_content', '').strip()
        expansion_type = data.get('expansion_type', 'general')
        expansion_focus = data.get('expansion_focus', 'comprehensive')
        
        if not initial_content:
            return jsonify({'error': 'Initial content is required'}), 400
        
        # Build the extension prompt
        if expansion_focus == 'comprehensive':
            prompt = build_extension_prompt(initial_content, expansion_type)
        else:
            prompt = build_detailed_expansion_prompt(initial_content, expansion_focus)
        
        # Use the content generator to extend the content
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        
        result_obj = loop.run_until_complete(
            generator.generate_from_prompt(prompt, preferred_provider=None)
        )
        
        if result_obj.success:
            return jsonify({
                'result': result_obj.content,
                'provider_used': result_obj.provider,
                'success': True
            })
        else:
            return jsonify({
                'error': result_obj.error_message or 'Failed to extend content',
                'success': False
            }), 500
            
    except Exception as e:
        logger.error(f"Error extending content: {str(e)}")
        return jsonify({
            'error': 'Internal server error',
            'success': False
        }), 500

@app.route('/health')
def health_check():
    """Health check endpoint"""
    return jsonify({'status': 'healthy', 'service': 'extension-service'})

if __name__ == '__main__':
    # Check if API keys are configured
    try:
        settings = Settings()
        if not settings.is_any_api_key_set():
            print("Warning: No API keys are configured. Please configure API keys in local_config.py")
        else:
            print(f"API keys configured for providers: {settings.get_active_providers()}")
    except Exception as e:
        print(f"Could not load settings: {e}")
    
    print("Starting CopySpell AI Extension Service on port 5001...")
    print("Access the service at: http://localhost:5001")
    print("API endpoint: POST /api/extend")
    
    app.run(host='0.0.0.0', port=5001, debug=False, threaded=True)